### ISSUE TITLE
用新版 Carthage 编译出的 xcframework 无法使用

### ISSUE THREAD

**Issue by lexrus** [SDWebImage/libwebp-Xcode#8]
新版 Carthage 支持编译 xcframework，用以下命令可以成功编译出 libwebp.xcframework:
`carthage --use-xcframeworks --no-use-binaries --platform iOS`

但是到拖进项目里用，编译的时候会遇到这个问题：
<img width="651" alt="Screen Shot 2021-03-17 at 10 49 11 PM" src="https://user-images.githubusercontent.com/219689/111487066-00d6d480-8773-11eb-8653-9d05500273e7.png">

示例项目在此：
https://github.com/lexrus/LibWebpXCDemo

麻烦大佬帮忙看看有什么办法解决。

**Comment by lexrus** [comment]
用了你 podspec 文件里的这句命令之后可以了，打扰了。
`sed -i.bak 's/<inttypes.h>/<stdint.h>/g' './src/webp/types.h'`

**Comment by dreampiggy** [comment]
Seems this is because of libwebp's source code compatible with clang module.

I have no way to fix it without modifing their souce code (we use Git submodule with tag). So only fix the CocoaPods's one.

For Carthage/SwiftPM, try to disable the clang module or enabling the `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES`
